fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
    - id: mypy
      pass_filenames: false
      args: [ '.' ]
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: hatch run dev:pytest tests/
      language: system
      types: [ file, python ]
