fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: hatch run dev:black
      language: system
      types: [file, python]
    - id: isort
      name: isort
      entry: hatch run dev:isort
      language: system
      types: [file, python]
    - id: ruff-check
      name: ruff-check
      entry: hatch run dev:ruff check
      language: system
      types: [ file, python ]
    - id: pytest
      name: pytest
      entry: hatch run dev:pytest tests/
      language: system
      types: [ file, python ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      - id: check-yaml