[project]
name = "mite_extras"
version = "1.6.6"
description = "Parsing, conversion, and validation functionality for Minimum Information about a Tailoring Enzyme (MITE) files."
readme = "README.md"
requires-python = ">=3.12.0,<3.13.0"  # because of rdkit 2024
license-files = ["LICENSE"]
authors = [
  { name = "Mitja M. Zdouc", email = "zdoucmm@gmail.com" },
  { name = "Adriano Rutz", email = "adafede@gmail.com" }
]
keywords = ["cheminformatics", "genomics"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Topic :: Scientific/Engineering :: Chemistry"
]
dependencies = [
  "coloredlogs~=15.0",
  "json-repair~=0.61",
  "mite-schema>=1.8.4",
  "pydantic~=2.13",
  "rdkit==2024.3.6",
  "requests~=2.34",
]

[project.urls]
Github = "https://github.com/mite-standard/mite_extras"
Homepage = "https://mite.bioinformatics.nl/"
Issues = "https://github.com/mite-standard/mite_extras/issues"

[project.scripts]
mite_extras = "mite_extras.main:main_cli"

[project.optional-dependencies]
dev = [
  "prek>=0.4.9",
]

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "-ra -q"
minversion = "6.0"
pythonpath = ["src/mite_extras"]
testpaths = [
  "tests",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
  # flake8-bugbear
  "B",
  # flake8-comprehensions
  "C4",
  # flake8-eradicate/eradicate
  "ERA",
  # isort
  "I",
  # pep8-naming
  "N",
  # flake8-pie
  "PIE",
  # pygrep
  "PGH",
  # ruff checks
  "RUF",
  # flake8-simplify
  "SIM",
  # flake8-type-checking
  "TCH",
  # flake8-tidy-imports
  "TID",
  # pyupgrade
  "UP",
]
ignore = [
  # whitespace-before-punctuation
  "E203",
  # percent-format-invalid-format
  "E501",
  # mixed-case-variable-in-class-scope
  "N815",
  # needless-boool
  "SIM103"
]
